### ISSUE TITLE
vocab_size mismatch

### ISSUE THREAD

**Issue by mohit-rathod** [NormXU/DocParser-Pytorch#4]
Hey,

I have trained the DocParser model on my custom dataset to predict some new entities using your code. Model is trained successfully. But during inference time, I am getting the size mismatch. I figured out that there are few more tokens added to the model and those are the tokens that I want to predict on my dataset. 

How can I update the code for inference to predict the new tokens?

I got this error 

RuntimeError: Error(s) in loading state_dict for VisionEncoderDecoderModel:
        size mismatch for decoder.model.decoder.embed_tokens.weight: copying a param with shape torch.Size([57552, 1024]) from checkpoint, the shape in current model is torch.Size([57525, 1024]).
        size mismatch for decoder.lm_head.weight: copying a param with shape torch.Size([57552, 1024]) from checkpoint, the shape in current model is torch.Size([57525, 1024]).

**Comment by Mohamed-Dhouib** [comment]
Hello, You need to save the tokenizer  (if not already done) and load the saved version before loading the weights

**Comment by mohit-rathod** [comment]
> Hello, You need to save the tokenizer (if not already done) and load the saved version before loading the weights

Can you help on how to load the tokenizer? where I need to make changes?

**Comment by mohit-rathod** [comment]
Can you tell why the model is always giving {'text_sequence': ''} as the output regardless of any token asked to be predicted?

**Comment by NormXU** [comment]
@mohit-rathod Sorry for the late reply. Could you check the input IDs and confirm if the labels are appropriately masked as expected? If they are, there might be a dataset bias to consider I guess.
